# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0001_initial'),
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to='login_and_registration_app.User'),
        ),
    ]
