# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='student',
        ),
    ]
